INSERT INTO SUBJECT values(1,'Applied Chemistry');
INSERT INTO SUBJECT values(2,'Computer Programming');
INSERT INTO SUBJECT values(3,'Electrical Engineering');
INSERT INTO SUBJECT values(4,'Energy and Environment');
INSERT INTO SUBJECT values(5,'Mathematics-I');
INSERT INTO SUBJECT values(6,'Mechanics');
INSERT INTO SUBJECT values(7,'Applied Physics');
INSERT INTO SUBJECT values(8,'Object Oriented Programming');
INSERT INTO SUBJECT values(9,'Electronics Engineering');
INSERT INTO SUBJECT values(10,'Engineering Drawing');
INSERT INTO SUBJECT values(11,'Professional Communication');
INSERT INTO SUBJECT values(12,'Mathematics-II');
INSERT INTO SUBJECT values(13,'Data Structures');
INSERT INTO SUBJECT values(14,'Design and Analysis of Algorithms');
INSERT INTO SUBJECT values(15,'Digital Electronics');
INSERT INTO SUBJECT values(16,'Software Engineering');
INSERT INTO SUBJECT values(17,'Computer Graphics');
INSERT INTO SUBJECT values(18,'Compiler Construction');
INSERT INTO SUBJECT values(19,'Project Semester');
INSERT INTO SUBJECT values(20,'Machine Learning');
INSERT INTO SUBJECT values(21,'Parallel Computing');
INSERT INTO SUBJECT values(22,'Advanced Software Engineering ');
INSERT INTO SUBJECT values(23,'VSLI Design');
INSERT INTO SUBJECT values(24,'Optimisation Techniques');
INSERT INTO SUBJECT values(25,'Optimisation Process');
INSERT INTO SUBJECT values(26,'Operating Systems');
INSERT INTO SUBJECT values(27,'Capstone Project');
INSERT INTO SUBJECT values(28,'Signal and System');
INSERT INTO SUBJECT values(29,'Digital System Design');
INSERT INTO SUBJECT values(30,'Analog Electronic Circuit');
INSERT INTO SUBJECT values(31,'MOS Circuit Design');
INSERT INTO SUBJECT values(32,'Numerical Analysis');
INSERT INTO SUBJECT values(33,'Power System Analysis');
INSERT INTO SUBJECT values(34,'System Theory');
INSERT INTO SUBJECT values(35,'Power System Protection');
INSERT INTO SUBJECT values(36,'Power System Dynamics');
INSERT INTO SUBJECT values(37,'Manufacturing Process');
INSERT INTO SUBJECT values(38,'Mechatronics');
INSERT INTO SUBJECT values(39,'Industrial Engineering');
INSERT INTO SUBJECT values(40,'Introduction to Automation');
INSERT INTO SUBJECT values(41,'Introduction to ThermoFluids');
INSERT INTO SUBJECT values(42,'Machine Design');
INSERT INTO SUBJECT values(43,'Robotics');
INSERT INTO SUBJECT values(44,'Minor Project');
INSERT INTO SUBJECT values(45,'Energy Resources');
INSERT INTO SUBJECT values(46,'Industrial Pollution');
INSERT INTO SUBJECT values(47,'Process Instrumentation and Control');
INSERT INTO SUBJECT values(48,'Analysis of Transport Phenomenon');
INSERT INTO SUBJECT values(49,'Chemical Reactor Theory');
INSERT INTO SUBJECT values(50,'Environmental Management');
INSERT INTO SUBJECT values(51,'Solvent Extraction');
select * from subject
